"""Generate self-hosted CJK subsets from the FandolKai Regular OTF.
Usage: python scripts/build_kai_webfont.py /path/to/FandolKai-Regular.otf
Requires fonttools[woff]. The derived font is renamed Homepage Kai.
"""
from pathlib import Path
import hashlib
import sys
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
source = Path(sys.argv[1])
out = ROOT / 'static/fonts/homepage-kai'
out.mkdir(parents=True, exist_ok=True)

def is_cjk(n):
    return any(a <= n <= b for a, b in [(0x2E80, 0xA4CF), (0xF900, 0xFAFF), (0xFE10, 0xFE1F), (0xFE30, 0xFE4F), (0xFF00, 0xFFEF), (0x20000, 0x323AF)])

def chars(text):
    return {ord(c) for c in text if is_cjk(ord(c))}

def ranges(points):
    result = []
    start = end = None
    for n in sorted(points):
        if end is not None and n == end + 1:
            end = n
        else:
            if start is not None:
                result.append(f'U+{start:X}' if start == end else f'U+{start:X}-{end:X}')
            start = end = n
    if start is not None:
        result.append(f'U+{start:X}' if start == end else f'U+{start:X}-{end:X}')
    return ','.join(result)

with TTFont(source) as font:
    available = {n for n in font.getBestCmap() if is_cjk(n)}
preview = chars('赵海萌')
body = set()
for path in (ROOT / 'content').rglob('*'):
    if path.suffix not in ('.md', '.json'):
        continue
    text = path.read_text()
    body |= chars(text)
    if path.suffix == '.md':
        preview |= chars(text.split('---', 2)[1] if text.startswith('---') else '')
missing = body - available
print('CJK source characters not covered:', ''.join(map(chr, sorted(missing))))
groups = [('preview', preview & available), ('articles', (body - preview) & available)]
rest = sorted(available - preview - body)
groups += [(f'extended-{i // 1024:02}', set(rest[i:i+1024])) for i in range(0, len(rest), 1024)]
css = ['// Generated by scripts/build_kai_webfont.py; see font directory for license and provenance.']
for name, points in groups:
    if not points:
        continue
    font = TTFont(source)
    options = subset.Options()
    options.flavor = 'woff2'
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=points)
    sub.subset(font)
    # Preserve copyright/license records; use a new family name for derived subsets.
    names = {1: 'Homepage Kai', 2: 'Regular', 3: 'Homepage Kai Regular 0.3', 4: 'Homepage Kai Regular', 6: 'HomepageKai-Regular', 16: 'Homepage Kai', 17: 'Regular'}
    for record in font['name'].names:
        if record.nameID in names:
            record.string = names[record.nameID].encode(record.getEncoding())
    font.flavor = 'woff2'
    font.save(out / f'fandol-{name}.woff2')
    css.append('@font-face {\n  font-family: "Homepage Kai";\n  font-style: normal;\n  font-weight: 400;\n  font-display: swap;\n  src: url("../fonts/homepage-kai/fandol-' + name + '.woff2") format("woff2");\n  unicode-range: ' + ranges(points) + ';\n}')
    print(name, len(points), (out / f'fandol-{name}.woff2').stat().st_size)
(ROOT / 'assets/scss/_kai-font.scss').write_text('\n'.join(css) + '\n')
(out / 'README.md').write_text('''# Homepage Kai webfont

Derived from FandolKai Regular v0.3 by the Fandol team (Clerk Ma and Jie Su).
Source: https://ctan.org/pkg/fandol
License: GPL v3 with font exception; see COPYING and UPSTREAM-README.txt.
The upstream OTF and subset build script are included in this directory.

The derived family is renamed Homepage Kai. Changes: CJK-only subsetting,
WOFF2 compression, font family renaming. Glyph outlines are unchanged.
Preview and article characters load separately; remaining glyphs are split into
1024-character subsets. CSS unicode-range loads only the needed subsets.
Latin text continues to use Google Sans. No third-party font requests are needed.

Rebuild with scripts/build_kai_webfont.py and fonttools[woff].
Source OTF SHA-256: ''' + hashlib.sha256(source.read_bytes()).hexdigest() + '\n')
